# Generated by Django 3.0 on 2023-02-15 16:59

from django.db import migrations

from lettings.models import Letting


def import_lettings(apps, schema):
    old_letting = apps.get_model('oc_lettings_site', 'Letting')
    old_lettings = old_letting.objects.all()
    for letting in old_lettings:
        del letting._state
        new_letting = Letting(**letting.__dict__)
        new_letting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_auto_20230215_1746'),
        ('oc_lettings_site', '0002_auto_20230215_1709'),
    ]

    operations = [
        migrations.RunPython(import_lettings),
    ]
